version: "3.0"

# Application Services
services:
  # PHP Service
  app:
    container_name: movies-php
    image: "ghcr.io/mutlaqaldhbuiub/movies"
    volumes:
      - persistent:/var/www/html:delegated
      - /home/movies/storage/:/var/www/html/storage/:delegated
    environment:
      SERVICE_NAME: api
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - movies_new_network
    env_file:
      - stack.env

#Docker Networks
networks:
  movies_new_network:
    driver: bridge

volumes:
  persistent: {}